server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: Add specific headers or other configurations if needed
    # Example: Caching for static assets
    # location ~* \.(?:jpg|jpeg|gif|png|ico|css|js)$ {
    #     expires 7d;
    #     add_header Pragma public;
    #     add_header Cache-Control "public";
    # }
}
